config/routes.rb
Rails.application.routes.draw do

  get '/map' => 'map#index'
  get '/mapdata' => 'map#map'

  devise_for :users, controllers: { sessions: "users/sessions" }


  resources :users do
    resources :products
  end


  root 'welcome#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user

	geocoded_by :address
	after_validation :geocode

	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :products
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
  	user_path(current_user)
	end


protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation) } 
	end


  protect_from_forgery with: :exception


private 
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(request.referrer || root_path)
  end  
end

app/controllers/map_controller.rb
class MapController < ApplicationController

	def index
	  @products = Product.all
	end
  
  def map
  	@products = Product.all
  	respond_to do |format|
  		format.html
  		format.json {render json: @products}
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_user
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :new_product, only: [ :new, :create ]

  def index
    @products = Product.all
  end

  def new
    authorize @product
    @product = Product.new
  end

  def create
    authorize @product
    product_params = params.require(:product).permit(:kind, :description, :photo, :address, :latitude, :longitude, :price, :availability)
    product = Product.create(product_params)
    @user.products << product
    redirect_to [@user, product]
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    product_params = params.require(:product).permit(:kind, :description, :photo, :address, :latitude, :longitude, :price, :availability)
    @product.update(product_params)
    redirect_to user_products_path
  end

  def show
    authorize @product
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to user_products_path, Notice: "The product was successfully destroyed."
  end

private
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def new_product
    @product = Product.new(user_id: params[:user_id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #  super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swuit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <!-- Google Web Font -->
  <link href='http://fonts.googleapis.com/css?family=Orbitron:900' rel='stylesheet' type='text/css'>

  <!-- START MAPBOX -->
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.css' rel='stylesheet' />

  <!-- END MAPBOX -->

  <!-- start Mixpanel -->

  <script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("3d3d3fc486d9029386fa93fa04b56a35");</script>

<script type="text/javascript">
mixpanel.track("Sign in");
</script>

<script type="text/javascript">
mixpanel.track("Sign out");
</script>

<script type="text/javascript">
mixpanel.track("Sign up");
</script>

<!-- end Mixpanel -->

</head>

<body class="color">
  <!-- start top navbar -->
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <div class="nav navbar-right nav pull-left">
          <%= link_to('<i class="fa fa-home fa-lg"></i>'.html_safe, root_path, class: "btn btn-success")  %>
            <% if user_signed_in? %>
              <%= link_to('<i class="fa fa-cogs fa-lg"></i>'.html_safe, user_path(current_user), class: "btn btn-info") %>
              <%= link_to('<i class="fa fa-map-marker fa-lg"></i>'.html_safe, map_path, class: "btn btn-info") %>
              <%= link_to('<i class="fa fa-power-off fa-lg"></i>'.html_safe, destroy_user_session_path, :method => :delete, class: "btn btn-danger") %>  
            <% else %>
              <%= link_to('<i class="fa fa-user fa-lg"></i>'.html_safe, new_user_session_path, class: "btn btn-success")  %>
              <%= link_to('<i class="fa fa-user-plus fa-lg"></i>'.html_safe, new_user_registration_path, class: "btn btn-warning") %>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
  <!-- end top navbar -->

  <div class="container">
    <br><br><br>
    <%= yield %>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>

</body>
</html>

app/views/map/index.html.erb
<div class="homefont">
	<h1>products by location</h1>
</div>

<%= javascript_include_tag 'theMap', 'data-turbolinks-track' => true %>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			<div class="table-responsive">
				<table class="table table-hover">
					<tbody>
						<% @products.each do |product| %>
							<tr>
							  <td>
							  	<%= link_to product.kind, user_product_path(product.user, product), class: "btn btn-default" %>
							  </td>
							</tr>  
						<% end %>
					</tbody>	
				</table>
			</div>	
		</div>
		<div class="col-md-10">
			<div id='map'>
			</div>
		</div>	
	</div>
</div>

app/views/products/_form.html.erb
<%= simple_form_for [@user, @product] do |f| %>
	
	<div class="field">
		<%= f.input :kind, :input_html => {:style=> 'width: 400px'} %>
		<%= f.input :description, :input_html => {:style=> 'width: 400px'} %>
		<%= f.input :photo, as: :file %>
		<%= f.input :address, :input_html => {:style=> 'width: 400px'}, placeholder: 'EX: 1853 Solano Avenue, Berkeley, CA 94707' %>
		<%= f.input :latitude, :as => :hidden, :input_html => { :value => "some value" } %>
		<%= f.input :longitude, :as => :hidden, :input_html => { :value => "some value" } %>
		<%= f.input :price, :input_html => {:style=> 'width: 400px'} %>
		<%= f.input :availability, :input_html => {:style=> 'width: 100px'} %>
		<%= f.button :submit %>
	</div>

<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="homefont">
	<h1>edit your product</h1>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="homefont">
	<h1>products</h1>
</div>
<div class="row">
	<div class ="context">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>These are all of the products belonging to <%= @user.first_name %>:</h3>
			</div>	
			<div class="panel-body">
				<% @user.products.each do |product|  %> 
					<%= link_to("show", [@user, product], class: "btn btn-success") if policy(product).show? %>
					<%= link_to("edit", edit_user_product_path(@user, product), class: "btn btn-success") if policy(product).edit? %>
					<%= link_to("delete", [@user, product], class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this?" }) if policy(product).destroy? %> 
					<%= product.kind %>
					<p>&nbsp;</p>
				<% end %>
			</div>
		</div>	
	</div>
</div>

app/views/products/new.html.erb
<div class="homefont">
	<h1>register your product</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="homefont">
	<h1>Product details</h1>
</div>
<div class="row">
	<div class ="context">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>Kind: <%= @product.kind %></h3>
			</div>	
			<div class="panel-body">
				<h3>Description: <%= @product.description %> </h3>
				<%= image_tag @product.photo.url(:medium) %> <br>
				<h3>Address: <%= @product.address %> </h3>
				<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=15&markers=#{@product.latitude}%2C#{@product.longitude}" %>
				<h3>Price: <%= @product.price %> </h3>
				<h3>Availability: <%= @product.availability.strftime("%B %e, %Y at %l:%M%p") %> </h3>
				<h3>Contact me: <%= @user.email %> or <%= @user.phone %></h3>
			</div>
		</div>	
	</div>
	<%= link_to("edit", edit_user_product_path(@user, @product), class: "btn btn-success") if policy(@product).edit? %>
	<%= link_to("delete", [@user, @product], class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this?" }) if policy(@product).destroy? %> 
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="homefont">
	<h1>Hello,</h1>
</div>
<div class="row">
	<div class ="context">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3><%= @user.first_name %></h3>
			</div>	
			<div class="panel-body">
				<%= link_to("add product", new_user_product_path(current_user), class: "btn btn-success") %>
				<%= link_to("your products", user_products_path(current_user), class: "btn btn-info") %>
			</div>
		</div>	
	</div>
</div>		

app/views/welcome/index.html.erb
<div class="homefont">

	<h1>do you swuit?</h1>
	    
	<%= image_tag("home-image.png") %>

</div>